version: 2.1

description: Build and publish good-pizza-club

jobs:
  build:
    working_directory: ~/good-pizza-club
    docker:
      - image: cimg/node:14.17.6-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: v1-npm-deps-{{ checksum "package-lock.json" }}
          paths:
              - ./node_modules
      - run:
          name: "Lint code"
          command: "npm run lint"
      # - run:
      #    name: "test code"
      #    command: "npm run test -- --progress false --watch false"
      - run:
          name: "Build artifact"
          command: "npm run build -- -c production  --progress false"

  deploy:
    working_directory: ~/good-pizza-club
    docker:
      - image: cimg/node:14.17.6-browsers
    steps:
      - run:
          name: Firebase Deploy
          command: ./node_modules/.bin/firebase deploy --token "$FIREBASE_TOKEN" --only hosting


workflows:
  build-deploy-workflow:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - main
