version: 2.1

description: Build and publish good-pizza-club

jobs:
  lint_and_test:
    working_directory: ~/good-pizza-club
    docker:
      - image: cimg/node:14.17.6-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-npm-deps-{{ .Branch }}-{{ checksum "package.json" }}
            - v1-npm-deps-
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: v1-npm-deps-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
              - ./node_modules
              -  ~/.cache/Cypress
      - run:
          name: "Lint code"
          command: "npm run lint"
      - run:
          name: "test code"
          command: "npm run test"
      - run:
          name: "E2E test cases"
          command: "./node_modules/.bin/cypress install && npm run cypress:ci"

  build-deploy:
    working_directory: ~/good-pizza-club
    docker:
      - image: cimg/node:14.17.6-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-npm-deps-{{ checksum "package.json" }}
            - v1-npm-deps-
      - run:
          name: "Build artifact"
          command: "npm run build -- -c production  --progress false"
      - run:
          name: Firebase Deploy
          command: ./node_modules/.bin/firebase deploy --token "$FIREBASE_TOKEN" --only hosting


workflows:
  build-deploy-workflow:
    jobs:
      - lint_and_test
      - build-deploy:
          requires:
            - lint_and_test
          filters:
            branches:
              only:
                - main
